# creating the system setup tasks for the common role and added the task for installing the nodejs and its dependencies for the catalogue service.
- name: copy {{ component }} service
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: daemon reload

- name: start the service # here i am starting the service and enabling it to start on boot.
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes